# services/pdf.py
import io
import os
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch

REACT_APP_URL = os.getenv("REACT_APP_URL", "http://localhost:3000")


def generate_certificate_pdf(
    artist: str, title: str, sha256: str, phash: str,
    asset_id: str, timestamp: str, email: str
) -> bytes:
    buf  = io.BytesIO()
    doc  = SimpleDocTemplate(buf, pagesize=A4,
                             rightMargin=50, leftMargin=50,
                             topMargin=50,   bottomMargin=50)
    teal = colors.HexColor("#0D9488")
    navy = colors.HexColor("#1A73E8")
    lt   = colors.HexColor("#F1F3F4")
    mute = colors.HexColor("#5F6368")

    h1   = ParagraphStyle("h1",   fontSize=22, textColor=navy,  fontName="Helvetica-Bold", spaceAfter=4)
    sub  = ParagraphStyle("sub",  fontSize=11, textColor=teal,  fontName="Helvetica",      spaceAfter=2)
    note = ParagraphStyle("note", fontSize=8,  textColor=mute,  fontName="Helvetica",      leading=12)

    rows = [
        ["Artist / Creator",    artist],
        ["Artwork Title",       title],
        ["Owner Email",         email],
        ["Asset ID",            asset_id],
        ["Registered At (UTC)", timestamp],
        ["SHA-256 Hash",        sha256],
        ["Perceptual Hash",     phash],
    ]
    tbl = Table(rows, colWidths=[1.8 * inch, 5 * inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",     (0, 0), (0, -1), lt),
        ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, -1), 9.5),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, lt]),
        ("GRID",           (0, 0), (-1, -1), 0.4, colors.HexColor("#E0E0E0")),
        ("PADDING",        (0, 0), (-1, -1), 9),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
    ]))

    story = [
        Paragraph("🛡️  PixelGuard", h1),
        Paragraph("Digital Artwork Ownership Certificate", sub),
        HRFlowable(width="100%", thickness=1.5, color=navy, spaceAfter=20),
        tbl,
        Spacer(1, 20),
        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E0E0E0"), spaceAfter=10),
        Paragraph(
            "This certificate is timestamped by Firebase (Google Cloud) servers and cannot be backdated. "
            "The SHA-256 hash is a cryptographic fingerprint of the original file. "
            "The pHash identifies visually similar copies even after editing, cropping, or watermark removal. "
            f"Verify at: {REACT_APP_URL}?verify={asset_id}",
            note
        ),
        Spacer(1, 6),
        Paragraph("Generated by PixelGuard · Powered by Google Firebase, Gemini AI & Cloud Vision", note),
    ]
    doc.build(story)
    return buf.getvalue()


def generate_dmca_pdf(
    artist: str, title: str, asset_id: str,
    cert_ts: str, violations: list
) -> bytes:
    buf   = io.BytesIO()
    doc   = SimpleDocTemplate(buf, pagesize=A4,
                               rightMargin=50, leftMargin=50,
                               topMargin=50,   bottomMargin=50)
    navy  = colors.HexColor("#1A73E8")
    red   = colors.HexColor("#EA4335")
    lt    = colors.HexColor("#F1F3F4")
    mute  = colors.HexColor("#5F6368")

    h1   = ParagraphStyle("h1",   fontSize=20, textColor=colors.HexColor("#202124"), fontName="Helvetica-Bold", spaceAfter=4)
    h2   = ParagraphStyle("h2",   fontSize=13, textColor=colors.HexColor("#202124"), fontName="Helvetica-Bold", spaceAfter=6)
    sub  = ParagraphStyle("sub",  fontSize=11, textColor=navy, fontName="Helvetica",  spaceAfter=12)
    body = ParagraphStyle("body", fontSize=10, textColor=colors.HexColor("#202124"), fontName="Helvetica", leading=15)
    note = ParagraphStyle("note", fontSize=8,  textColor=mute, fontName="Helvetica",  leading=12)

    meta = Table([
        ["Artist / Creator",            artist],
        ["Artwork Title",               title],
        ["PixelGuard Asset ID",         asset_id],
        ["Original Registration (UTC)", cert_ts],
    ], colWidths=[2.2 * inch, 4.3 * inch])
    meta.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), lt),
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9.5),
        ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#E0E0E0")),
        ("PADDING",    (0, 0), (-1, -1), 8),
    ]))

    story = [
        Paragraph("PixelGuard — Copyright Infringement Report", h1),
        Paragraph(f"Generated: {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", sub),
        HRFlowable(width="100%", thickness=1.5, color=navy, spaceAfter=12),
        Paragraph("Claimant Details", h2),
        meta,
        Spacer(1, 16),
        Paragraph(f"Infringements Identified: {len(violations)}", h2),
    ]

    for i, v in enumerate(violations, 1):
        risk_c = red if v.get("risk") == "High Risk" else colors.HexColor("#B45309")
        story.append(Paragraph(
            f"#{i} — {v.get('platform','?')} · {v.get('url','')[:70]}",
            ParagraphStyle("vt", fontSize=10, fontName="Helvetica-Bold",
                           textColor=risk_c, spaceAfter=4)
        ))
        vt = Table([
            ["URL",        v.get("url", "")],
            ["Platform",   v.get("platform", "")],
            ["Similarity", f"{v.get('similarity','')}%"],
            ["Risk Level", v.get("risk", "")],
            ["Status",     v.get("status", "Pending Review")],
        ], colWidths=[1.8 * inch, 4.7 * inch])
        vt.setStyle(TableStyle([
            ("BACKGROUND",     (0, 0), (0, -1), lt),
            ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",       (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, lt]),
            ("GRID",           (0, 0), (-1, -1), 0.4, colors.HexColor("#E0E0E0")),
            ("PADDING",        (0, 0), (-1, -1), 7),
        ]))
        story.append(vt)
        if v.get("gemini_summary"):
            story += [Spacer(1, 6), Paragraph(f"AI Analysis: {v['gemini_summary']}", body)]
        story += [
            Spacer(1, 12),
            HRFlowable(width="100%", thickness=0.3,
                       color=colors.HexColor("#E0E0E0"), spaceAfter=10)
        ]

    story += [
        Spacer(1, 10),
        Paragraph(
            "HOW TO USE: Send this PDF + your ownership certificate to the platform's DMCA team. "
            "Etsy: help.etsy.com/hc/en-us/requests/new · Redbubble: redbubble.com/about/ip-policy "
            "· Instagram: help.instagram.com. You must include: 'I have a good faith belief that "
            "use of this material is not authorised by the copyright owner, its agent, or the law.'",
            note
        ),
        Spacer(1, 6),
        Paragraph("Generated by PixelGuard · Powered by Google Firebase & Gemini AI", note),
    ]
    doc.build(story)
    return buf.getvalue()
